version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    #restart: always
    ports: 
      - 51663:1972
      - 52663:52773
      - 53773
    #network_mode: "host"
    volumes:
    #  - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
